# Generated by Django 4.1.9 on 2023-05-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_job_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
