# Generated by Django 4.1.9 on 2023-06-21 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0003_job_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="players",
            field=models.ManyToManyField(
                null=True, related_name="related_jobs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
