# Generated by Django 4.1.9 on 2023-06-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_job_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
