[tool.poetry]
package-mode = false
name = "beckoningmu"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
evennia = {extras = ["extras"], version = "^4.1.1"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

