# Generated by Django 4.1.9 on 2023-05-29 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "read_perm",
                    models.CharField(
                        default="all",
                        help_text="Permission required to read this board.",
                        max_length=200,
                    ),
                ),
                (
                    "write_perm",
                    models.CharField(
                        default="all",
                        help_text="Permission required to post to this board.",
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "read_perm",
                    models.CharField(
                        default="all",
                        help_text="Permission required to read this post.",
                        max_length=200,
                    ),
                ),
                (
                    "write_perm",
                    models.CharField(
                        default="all",
                        help_text="Permission required to comment on this post.",
                        max_length=200,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="bbs.board",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "read_perm",
                    models.CharField(
                        default="all",
                        help_text="Permission required to read this comment.",
                        max_length=200,
                    ),
                ),
                (
                    "write_perm",
                    models.CharField(
                        default="all",
                        help_text="Permission required to comment on this comment.",
                        max_length=200,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="bbs.post",
                    ),
                ),
            ],
        ),
    ]
